title: "Lisp Korea"
url: "http://lispkorea.github.io"
description: "lisp korea"

repository: https://github.com/lispkorea/lispkorea.github.io

plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

Paths :
    home: /
    posts: /posts
    resources: /res
    feed: /feed
    commonlisp: /commonlisp
    racket: /racket
    clojure: /clojure
    res_bower: /bower_components

# ref: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:title
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
  sass_dir: _sass
