title: Lisp Korea
url: http://lispkorea.github.io
description: lisp korea

repository: https://github.com/lispkorea/lispkorea.github.io

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

Paths :
    home: /
    posts: /posts
    resources: /res
    feed: /feed
    commonlisp: /commonlisp

# ref: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:title
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
  sass_dir: _sass
